name: yolov3_deepsort
channels:
  - conda-forge
dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv==4.1.0
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.1.2
    - lxml
    - tqdm
    - seaborn
    - pillow
