name: tracker-cpu
channels:
  - conda-forge
dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv==4.1.0
  - pip:
    - tensorflow==2.0.1
    - lxml
    - tqdm
    - seaborn
    - pillow
